### ISSUE TITLE
Allow using integers with arbitrary bit size

### ISSUE THREAD

**Issue by Rexagon** [broxus/intellij-t-sol#16]
Solidity ABI allows the use of integers with arbitrary bit width (up to 256 bits). However, the plugin doesn't seem to be able to recognize such integers as a built-in type. It would be nice to have all built-in types covered completely.

![image](https://user-images.githubusercontent.com/7278479/224310884-55549565-f4f5-4cf9-b514-4ab45772d5f2.png)

**Comment by mbolotov** [comment]
Plugin cannot support this behavior because it is out of scope according to the [compiler api docs](https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#integers):

> int / uint: Signed and unsigned integers of various sizes. Keywords uintN and intN where N is a number from 8 to 256 in steps of 8 denotes the number of bits.
