### ISSUE TITLE
`Structure` pane displays the wrong content when another item is single-clicked in file tree

### ISSUE THREAD

**Issue by vp-mazekine** [broxus/intellij-t-sol#34]
# How to reproduce
1. Open a file (`ArrayHelper.tsol` in this example) for editing in IDE
2. Select the `Structure` pane to see elements in it
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/f1eee11c-fc7a-4e7b-b94a-4bd4baf5052f)
3. Now, switch back to `Project` pane and single-click on any other file in the file tree (e.g., `locklift.config.ts`)
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/422e5ea2-71cf-4747-a2b2-c4ef2462ec7d)
4. Go back to `Structure` pane to see that it now displays the contents of the `locklift.config.ts` file instead of `ArrayHelper.tsol`
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/fe8fcb2b-4160-4ca4-a827-0c849c92c7e8)
5. Click in the editing area to see that `Structure` pane went back to normal

# Expected behavior
`Structure` pane always displays the contents of the currently edited file

**Comment by mbolotov** [comment]
From the official docs:

> This tool window displays the structure of a file currently opened in the editor and having the focus, or **selected in the Project tool window**.
> 
> For diagrams, this tool window shows the diagram preview.
> 

https://www.jetbrains.com/help/idea/structure-tool-window-file-structure-popup.html

So closing this as it cannot be fixed at the plugin's side
