### ISSUE TITLE
Standard functions valueToGas() and gasToValue() are marked as undefined

### ISSUE THREAD

**Issue by cassandrus** [broxus/intellij-t-sol#36]
Here is the example:

![image](https://github.com/broxus/intellij-t-sol/assets/97176349/a29e9d54-ce02-419e-a1f7-666d66cf978e)

**Comment by mbolotov** [comment]
Could you please provide a link to the docs where those functions are described?

**Comment by cassandrus** [comment]
Sure. 
https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#gastovalue
https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#valuetogas
