### ISSUE TITLE
Wrong suggestions of contract members when it acts as a function argument

### ISSUE THREAD

**Issue by 30mb1** [broxus/intellij-t-sol#37]
When we use contract (or interface) variable in a local scope, its ok

![Screenshot from 2023-06-13 15-54-40](https://github.com/broxus/intellij-t-sol/assets/15921290/138f4078-a0e4-41d1-85ef-5dda92eaedf5)

But if we will try it inside function invocation, it will start to suggest everything ;(

![Screenshot from 2023-06-13 15-55-26](https://github.com/broxus/intellij-t-sol/assets/15921290/e9e082be-dc08-44d7-8166-aa987fed1542)

**Comment by mbolotov** [comment]
fixed in 1.4
