### ISSUE TITLE
Modifiers from contracts defined in node modules are not detected

### ISSUE THREAD

**Issue by 30mb1** [broxus/intellij-t-sol#38]
Here `reserve()` function is defined in `Reservable` contract. IDE marks it as `undefined`

![Screenshot from 2023-06-14 19-20-41](https://github.com/broxus/intellij-t-sol/assets/15921290/a7566349-224c-46ce-b46c-754e257826a8)

**Comment by mbolotov** [comment]
fixed in 1.4
