### ISSUE TITLE
Use inline code refactoring instead of popups

### ISSUE THREAD

**Issue by vp-mazekine** [broxus/intellij-t-sol#39]
# Current behavior
* User presses Shift+F6 on the desired word
* Popup appears showing refactoring options
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/41d35e57-2ffe-4350-b89b-ee4187f2bfeb)
* User inputs new name and clicks OK to finalize the refactoring

# Expected behavior
* User presses Shift+F6 on the desired word
* IDE enters the dynamic refactoring mode and highlights the word and all its mentions in the code
* User changes the word and presses ENTER to finalize
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/8861bf38-076a-4732-bd7f-513b0bd01f6d)
* OR user presses ESC to cancel editing

**Comment by mbolotov** [comment]
implemented in 1.4
