### ISSUE TITLE
Sort import definitions after applying the suggested import

### ISSUE THREAD

**Issue by vp-mazekine** [broxus/intellij-t-sol#40]
# Current behavior
After applying the suggested import in IDE (Alt+Enter), the new definition is added to the end of the imports list:
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/88bf4b18-b925-44cd-83d6-3de059816918)

# Expected behavior
The imports list is automatically sorted after adding a new entry:
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/6cb9ce5c-0146-43f6-bc41-a7cce34f1b14)

**Comment by mbolotov** [comment]
implemented in 1.4
