### ISSUE TITLE
Add SPDX License suggestions

### ISSUE THREAD

**Issue by vp-mazekine** [broxus/intellij-t-sol#41]
# Existing behavior
T-Sol allows indication of the applicable [SPDX](https://spdx.org/licenses/) code for the license used: 
![image](https://github.com/broxus/intellij-t-sol/assets/59574999/559de786-fce6-4768-b738-2c7ca10bb7c4)

However, no auto-suggest for available licenses is available at the moment.

# Expected behavior
1. [x] Upon entering the `// SPDX-License-Identifier: ` automatically suggest the list of SPDX license codes with dynamic filtering upon typing
2. [ ] Analyze the most frequently used license code throughout the codebase of the project and, if the license code of the current file differs, suggest either (a) updating it to the most frequently used or (b) applying the license code from this file to other files in the project
3. [ ] If SPDX code is specified anywhere in the source code tree, recommend adding it to all missing files.

**Comment by mbolotov** [comment]
task 1 implemented in 1.4 version
