### ISSUE TITLE
When using vector(<Some Type>) plugin loses type information.

### ISSUE THREAD

**Issue by cassandrus** [broxus/intellij-t-sol#49]
When I use a variable of struct type, I have information about its methods like unpack();

```
struct Limits {uint l; uint r;}
Limits l = Limits(0, res.length - 1);
l.unpack();
```

If I acquire the same type from vector, plugin loses type info: 

```
vector(Limits) s;
s.pop().unpack(); // shows error
```

Here's the full image:
![image](https://github.com/broxus/intellij-t-sol/assets/97176349/71dbc21c-2b60-4b08-b6cf-71903e45cbed)

**Comment by mbolotov** [comment]
Hi Dima,
This is expected to be fixed in the next release. 
Meanwhile, you can try this bundle with the support for type parameters: 
[IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip](https://github.com/broxus/intellij-t-sol/files/12607665/IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip)

**Comment by cassandrus** [comment]
> Hi Dima, This is expected to be fixed in the next release. Meanwhile, you can try this bundle with the support for type parameters: [IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip](https://github.com/broxus/intellij-t-sol/files/12607665/IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip)

works in the snapshot, thanks

**Comment by mbolotov** [comment]
> > Hi Dima, This is expected to be fixed in the next release. Meanwhile, you can try this bundle with the support for type parameters: [IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip](https://github.com/broxus/intellij-t-sol/files/12607665/IntelliJ-T-Sol-1.5-SNAPSHOT-14.zip)
> 
> works in the snapshot, thanks


This release however brings some flaky false positive type checking errors. 
You can try this bundle which hides those errors: 
[IntelliJ-T-Sol-1.5-SNAPSHOT-18-.zip](https://github.com/broxus/intellij-t-sol/files/12765348/IntelliJ-T-Sol-1.5-SNAPSHOT-18.zip)
