### ISSUE TITLE
not support assembly

### ISSUE THREAD

**Issue by ilyar** [broxus/intellij-t-sol#51]
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma ever-solidity >= 0.71.0;

function _add(uint a, uint b) assembly pure returns (uint) {
  "ADD",
}

contract App {
  function add(uint a, uint b) external pure returns (uint) {
    return _add(a, b);
  }
}
```
![image](https://github.com/broxus/intellij-t-sol/assets/761285/dda907d9-838c-4227-a067-47e6223257ba)

> ';', <function visibility specifier>, <state mutability>, Identifier, externalMsg, functionID, inline, internalMsg, returns or '{' expected, got 'assembly'

**Comment by mbolotov** [comment]
fixed in `1.7` version
