### ISSUE TITLE
Lexer issue with optional params inside abi.decode

### ISSUE THREAD

**Issue by FairyFromAlfeya** [broxus/intellij-t-sol#7]
<img width="536" alt="Screenshot 2023-02-17 at 14 54 39" src="https://user-images.githubusercontent.com/44115243/219674625-771146ee-3aa5-4b71-9ad5-0886d74ebe8a.png">

**Comment by mbolotov** [comment]
you can try this bundle with the fix: 
[IntelliJ-T-Sol-1.2-SNAPSHOT1.zip](https://github.com/broxus/intellij-t-sol/files/10784307/IntelliJ-T-Sol-1.2-SNAPSHOT1.zip)

**Comment by FairyFromAlfeya** [comment]
Works ok on version 1.2
