### ISSUE TITLE
Types from tuple mismatch when passing them to function

### ISSUE THREAD

**Issue by FairyFromAlfeya** [broxus/intellij-t-sol#8]
<img width="842" alt="Screenshot 2023-02-17 at 14 56 51" src="https://user-images.githubusercontent.com/44115243/219675354-394a3013-ba7a-4e37-88c7-f2de7b711d95.png">

**Comment by mbolotov** [comment]
you can try this bundle with the fix: 
[IntelliJ-T-Sol-1.2-SNAPSHOT1.zip](https://github.com/broxus/intellij-t-sol/files/10784307/IntelliJ-T-Sol-1.2-SNAPSHOT1.zip)

**Comment by FairyFromAlfeya** [comment]
Works ok on version 1.2
