### ISSUE TITLE
Can not pass non-optional variable as optional param to function

### ISSUE THREAD

**Issue by FairyFromAlfeya** [broxus/intellij-t-sol#9]
<img width="878" alt="Screenshot 2023-02-17 at 15 02 43" src="https://user-images.githubusercontent.com/44115243/219676364-12f0e58d-e7bd-4928-a712-9e1f5171d5b4.png">
https://github.com/tonlabs/TON-Solidity-Compiler/blob/master/API.md#optionaltype

**Comment by mbolotov** [comment]
you can try this bundle with the fix: 
[IntelliJ-T-Sol-1.2-SNAPSHOT1.zip](https://github.com/broxus/intellij-t-sol/files/10784307/IntelliJ-T-Sol-1.2-SNAPSHOT1.zip)

**Comment by FairyFromAlfeya** [comment]
Works well on version 1.2
